FROM openjdk:8-jdk-alpine
MAINTAINER HECTORFABIOLAME
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY $(JAR_FILE) direccion-servicio-0.0.1-SNAPSHOT.jar
COPY $(JAR_FILE) cliente-servicio-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java", "-jar","/direccion-servicio-0.0.1-SNAPSHOT.jar" ]
ENTRYPOINT [ "java", "-jar","/cliente-servicio-0.0.1-SNAPSHOT.jar" ]