server:
  port: 7070
  
eureka:
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      routes:
       - id: cliente-service
         uri: lb://cliente-service
         predicates:
           - Path=/cliente/**
       - id: direccion-service
         uri: lb://direccion-service
         predicates:
           - Path=/direccion/**