spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: cliente-service
         uri: lb://cliente-service
         predicates:
           - Path=/cliente/**
       - id: direccion-service
         uri: lb://direccion-service
         predicates:
           - Path=/direccion/**